version: '3.9'
services:
  postgres:
    env_file:
      - dev.env
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    networks:
      - backend-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    env_file:
      - dev.env
    image: redis:latest
    container_name: cache
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "cache-cli", "ping" ]
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 10s
      start_interval: 5s
    volumes:
      - cache-data:/data
    networks:
      - backend-network
  minio:
    env_file:
      - dev.env
    restart: on-failure
    container_name: minio_container
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    environment:
      MINIO_BUCKET_NAME: testbucket
      MINIO_ROOT_USER: testtest
      MINIO_ROOT_PASSWORD: testtest
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 5s
      timeout: 30s
      retries: 3
      start_period: 10s
    networks:
      - backend-network
networks:
  backend-network:
volumes:
  postgres_data:
  minio_data:
  redis-data:
