name: Build and Push Docker Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        include:
          - image: ghcr.io/mentor_link
            dockerfile: ./Dockerfile
          - image: ghcr.io/mentor_link_ws
            dockerfile: ./DockerfileWs
    steps:
      - name: Debug Matrix
        run: |
          echo "Image: ${{ matrix.image }}"
          echo "Dockerfile: ${{ matrix.dockerfile }}"

      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Log in to the Container registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}

      - name: Debug Metadata
        run: |
          echo "Tags: ${{ steps.meta.outputs.tags }}"
          echo "Labels: ${{ steps.meta.outputs.labels }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ matrix.image }}:master
          labels: ${{ steps.meta.outputs.labels }}